# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none none none none none none none none none none none none none none none none none none none none none none none none none none

pr: none none none none none none none none none none none none none none none none none none none none none none none none none none

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: websites
    Artifacts:
    - name: Azure.ResourceManager.AppService
      safeName: AzureResourceManagerAppService
