# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none none none none none none none none none none none none none none none none none none none none none none none none none none

pr: none none none none none none none none none none none none none none none none none none none none none none none none none none

# These comments should stay.

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: appconfiguration
    Artifacts:
    - name: Azure.ResourceManager.AppConfiguration
      safeName: AzureResourceManagerAppConfiguration
