# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/openai
    - sdk/openai/ci.yml
    - sdk/openai/Azure.OpenAI.Inference

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/openai
    - sdk/openai/ci.yml
    - sdk/openai/Azure.OpenAI.Inference

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: openai
    ArtifactName: packages
    Artifacts:
    - name: Azure.OpenAI.Inference
      safeName: AzureOpenAIInference
