# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/core/
    - eng/
    exclude:
    - eng/mgmt/
    - eng/common/
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/core/
    - sdk/testcommon/
    - eng/
    - samples/
    exclude:
    - eng/mgmt/
    - eng/common/
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml@self
  parameters:
    ServiceDirectory: core
    BuildSnippets: false
    ArtifactName: packages
    Artifacts:
    - name: Azure.Core
      safeName: AzureCore
    - name: Azure.Core.Experimental
      safeName: AzureCoreExperimental
    - name: Azure.Core.Expressions.DataFactory
      safeName: AzureCoreExpressionsDataFactory
    - name: Microsoft.Azure.Core.NewtonsoftJson
      safeName: MicrosoftAzureCoreNewtonsoftJson
    - name: Microsoft.Azure.Core.Spatial
      safeName: MicrosoftAzureCoreSpatial
    - name: Microsoft.Azure.Core.Spatial.NewtonsoftJson
      safeName: MicrosoftAzureCoreSpatialNewtonsoftJson
    - name: Azure.Core.Amqp
      safeName: AzureCoreAmqp
    - name: System.ClientModel
      safeName: SystemClientModel
    CheckAOTCompat: true
    AOTTestInputs:
    - ArtifactName: Azure.Core
      ExpectedWarningsFilepath: /Azure.Core/tests/compatibility/ExpectedAotWarnings.txt
    TestSetupSteps:
    - template: /sdk/storage/tests-install-azurite.yml
    TestTimeoutInMinutes: 100
    TestDependsOnDependency: Azure.Core