parameters:
  - name: TargetDirectory
    type: string
  - name: CustomTestSteps
    type: object
    default: []
  - name: EnvVars
    type: object
    default: {}
  - name: TargetTags
    type: string
    default: ''

variables:
  - template: /eng/pipelines/templates/variables/globals.yml

stages:
  - stage: 'Test'
    jobs:
      - job: 'Test'

        strategy:
          matrix:
            Windows:
              Pool: 'azsdk-pool-mms-win-2022-1es-pt'
              Image: 'azsdk-pool-mms-win-2022-1espt'
            Linux:
              Pool: 'azsdk-pool-mms-ubuntu-2004-1es-pt'
              Image: 'azsdk-pool-mms-ubuntu-2004-1espt'
            Mac:
              Pool: 'Azure Pipelines'
              Image: 'macos-11'

        pool:
          name: $(Pool)
          vmImage: $(Image)

        steps:
          - template: /eng/pipelines/templates/steps/run-pester-tests.yml
            parameters:
              TargetDirectory: ${{ parameters.TargetDirectory }}
              CustomTestSteps: ${{ parameters.CustomTestSteps }}
              EnvVars: ${{ parameters.EnvVars }}
              TargetTags: ${{ parameters.TargetTags }}
